Design and simulation of PCR
TimothyStiles/poly pull request #183
Opened 2021-08-06 21:51 UTC by Koeng101

I need to go over docs for this code + more tests, but generally, this PCR functionality seems to work. 

I've added 3 functions in the PCR subpackage within /primers/:

- DesignPrimersWithOverhang
- DesignPrimers
- Simulate

These should cover the basic use cases for PCRing.

2021-08-09 22:23 UTC, TimothyStiles commented
@Koeng101 reviewing now and got rid of the silly code climate issues.

The six things left brought up from code climate are legit and should be fixed. Will review and add comments.

2021-08-09 22:32 UTC, TimothyStiles requested changes
Code quality overall looks good for the most part. There's a complex repeated block that should be turned into a helper function and overall this needs a lot more biological context before it's merged.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +
Needs comment for docs.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +
Needs comment for docs.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +func DesignPrimersWithOverhangs(sequence, forwardOverhang, reverseOverhang string, targetTm float64) (string, string) {
Needs comment for docs.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +func DesignPrimersWithOverhangs(sequence, forwardOverhang, reverseOverhang string, targetTm float64) (string, string) {
Can you also give some overview on how primer design works? What are overhangs and why are they needed?, etc.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +			for _, reverseLocation := range reverseLocationInts {
This block seems to be repeated three times in this loop based on very minimal conditionals. Can this be refactored into a helper function for better code clarity?

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +
This also needs more in-line context. Regular devs won't know anything about forward and reverse locations, minimal length, melting temp, overhangs or even what PCR is.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +	forwardLocations := make(map[int][]int)
explain what this is.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +	reverseLocations := make(map[int][]int)
explain what this is.

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +	minimalPrimers := make([]string, primerLength)
What are minimal primers here?

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +		for i := 10; primers.MeltingTemp(primer[len(primer)-i:]) < targetTm; i++ {
magic number. Why 10?

2021-08-09 22:32 UTC, TimothyStiles commented on primers/pcr/pcr.go
> +		// Use the minimal binding sites of the primer to find positions in the genome
What's a minimal binding site?

2021-08-18 02:35 UTC, isaacguerreir commented
Had added a PR to add more functions for this subpackage #188

2021-11-03 01:48 UTC, Koeng101 commented
I am closing this PR because I think a few things need to be changed with the PCR simulation (for example, multiple templates at once for multiplexing). These changes are non-trivial and there are other PRs to focus on right now. I will add it back when possible.

2021-11-03 01:48 UTC, closed without merging