Finish adding coverage for outstanding packages
TimothyStiles/poly pull request #248
Opened 2022-04-05 21:25 UTC by fergloragain

This PR brings the total test coverage of the project to 100%

To achieve this:

- Some publicly accessed functions were moved into vars so that we can manipulate flows in testing
- Some functions were simplified, e.g. directly returning the result of a boolean check rather than capturing the comparison result in a var and returning that, also it was possible to eliminate some unnecessary else blocks
- Some functions returned values along with an error. These functions were predominantly recursive in nature, and never actually returned a non-nil error, so the error return could be eliminated entirely
- The sequenceBreakFlag was both initialised and checked inside a loop, which was wrong, it needed to be initialised outside the loop and checked inside the loop, otherwise it would always have been tested against its initial value
- Some blocks of code were lifted out into separate functions to make them more testable
- The test data supplied for some tests was pretty nonsensical on my part, I was just feeding values in order to hit different branches of logic. I'm open to making the test data more realistic if anyone has any suggestions?
- Unfortunately I had to compress everything down into a single commit to make my rebase easier,  but hopefully I've covered most points in this PR description!

2022-04-08 20:11 UTC, TimothyStiles commented
@fergloragain I'm so excited about this one. @Koeng101 has a PR (#244 ) where he fixed some Genbank Error handling. Haven't had a chance to check yet but would there be any merge conflicts?

2022-04-11 21:40 UTC, fergloragain commented
@TimothyStiles there definitely are some conflicts with the genbank package, but I don't mind waiting for @Koeng101 to merge his changes and then I can rebase and resolve conflicts after :+1:

2022-04-13 13:57 UTC, fergloragain commented
@TimothyStiles alternatively, I could merge this now, and then rebase @Koeng101's branch for him after?

2022-04-16 18:44 UTC, TimothyStiles commented
> @TimothyStiles alternatively, I could merge this now, and then rebase @Koeng101's branch for him after?

@fergloragain this sounds great. Just checked and all tests pass with 100% coverage. 
Two things before merging:

1. I'll find some less messy test data for you.

2. Those functions that return values with an error that never that's non-nil were intentional. Idea being that we put some error handling in there and keep the IO syntax identical-ish across all functions.

2022-06-19 23:09 UTC, TimothyStiles commented
@fergloragain. Just finished merging @Koeng101 genbank parser rewrite into `dev` with #244. Resolving conflicts with this PR now.

2022-06-20 02:55 UTC, TimothyStiles requested changes
@fergloragain this is looking really good! I've merged and cleaned up #244 and am adding back the errors even if they return nil for the moment. Any thoughts on where to go from here?

2022-06-20 02:55 UTC, TimothyStiles commented on io/gff/gff.go
> +	end := strconv.Itoa(sequence.Meta.RegionEnd)
potential off-by-one error?

2022-06-20 02:55 UTC, TimothyStiles commented on io/gff/gff.go
> +		featureType := "unknown"
is this canonical in GFF?

2022-06-20 02:55 UTC, TimothyStiles commented on io/genbank/genbank.go
> +	readFileFn      = ioutil.ReadFile
should this be 'os.open' now?

2022-06-20 02:55 UTC, TimothyStiles commented on io/polyjson/polyjson.go
> +func (feature Feature) GetSequence() string {
re-add error

2022-06-20 02:55 UTC, TimothyStiles commented on io/polyjson/polyjson.go
> +func getFeatureSequence(feature Feature, location Location) string {
re-add error

2022-06-20 02:55 UTC, TimothyStiles commented on io/polyjson/polyjson.go
> +	buf.ReadFrom(file)
linter yelling to check error

2022-06-20 02:55 UTC, TimothyStiles commented on io/genbank/genbank.go
> +	logFatalFn      = log.Fatal
linted as dead-code

2022-06-20 02:55 UTC, TimothyStiles commented on io/genbank/genbank.go
> +	regexpCompileFn = regexp.Compile
linted as dead-code

2022-06-21 00:49 UTC, merged